blueprints/login.py
from database.connector import open_session, close_session
from database.tables import User
from flask import Blueprint, render_template
from glob import glob
from lib.admin_decorators import admin_login_required
from lib.config_loader import get_cluster_desc
from lib.email_notification import get_email_configuration, send_confirmation_request
import flask, flask_login, logging, subprocess


login_blueprint = Blueprint('login', __name__, template_folder='templates')


@login_blueprint.route('/login', methods=['GET', 'POST'])
@login_blueprint.route('/login?msg=<msg>', methods=['GET', 'POST'])
def login(msg=None):
    from initialization import User as InitUser, bcrypt
    if flask.request.method == 'GET':
        next_url = flask.request.args.get("next")
        return render_template("login/login.html", next_url=next_url, msg=msg)
    email = flask.request.form.get('email', "")
    password = flask.request.form.get('password', "")
    next_url = flask.request.form.get('next_url', "/")
    db_session = open_session()
    user_account = db_session.query(User).filter(User.email == email).first()
    redirect_url = ''
    # User login
    if (user_account is not None and user_account.user_authorized and
            bcrypt.check_password_hash(user_account.password, password)):
        user = InitUser()
        user.id = email
        flask_login.login_user(user)
        redirect_url = next_url if (next_url is not None and next_url != "None") else flask.url_for("app.home")
    else:
        redirect_url = flask.url_for("login.login", msg="You are not authorized to log in")
    close_session(db_session)
    return flask.redirect(redirect_url)


@login_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    cluster_desc = get_cluster_desc()
    if flask.request.method == 'GET':
        next_url = flask.request.args.get("next")
        return render_template("login/signup.html", next_url=next_url)
    email = flask.request.form['email']
    firstname = flask.request.form['firstname']
    lastname = flask.request.form['lastname']
    password = flask.request.form['password']
    confirm_password = flask.request.form['confirm_password']
    db_session = open_session()
    existing_email = db_session.query(User).filter(User.email == email).all()
    if password != confirm_password:
        return 'The two passwords are not identical!<a href="/signup">Try again</a>'
    if len(existing_email) > 0:
        return "Your email address '%s' already exists. <a href='/'>Try to login</a>" % email
    email_filters = cluster_desc['email_filters']
    filter_ok = len(email_filters) == 0
    for f in email_filters:
        if f in email:
            filter_ok = True
    if not filter_ok:
        return 'Wrong email address.\
                Your domain name is not in the authorized domains.\
                Please contact the administrator or <a href="/signup">try with another email address</a>'
    user = User()
    user.email = email
    user.firstname = firstname
    user.lastname = lastname
    user._set_password = password
    db_session.add(user)
    close_session(db_session)
    email_conf = get_email_configuration()
    if len(email_conf['smtp_server_url']) > 0 and email_conf['smtp_server_url'] != 'no_config':
        # Send an email to confirm the user email address
        send_confirmation_request(email, firstname)
    if cluster_desc['email_signup']:
        redirect_url = flask.url_for("login.confirmation_created_account")
    else:
        redirect_url = flask.url_for("login.wait_admin_approval")
    return flask.redirect(redirect_url)


@login_blueprint.route('/confirmation_created_account')
def confirmation_created_account():
    return render_template("login/confirmation_created_account.html")


@login_blueprint.route('/wait_admin_approval')
def wait_admin_approval():
    return render_template("login/wait_admin_approval.html")


@login_blueprint.route('/confirmation_authorized_account')
def confirmation_authorized_account():
    return render_template("login/confirmation_authorized_account.html")


@login_blueprint.route('/confirmation_email')
def confirmation_email():
    return render_template("login/confirmation_email.html")


@login_blueprint.route('/confirm_email/token/<token>')
def confirm_email(token):
    logger = logging.getLogger("LOGIN")
    logger.info("Receive the token '%s' to confirm email" % token)
    db_session = open_session()
    user_candidate = db_session.query(User).filter(User.email_confirmation_token == token).first()
    url = "Bad request: could not find the given token '%s'" % (token)
    if user_candidate is not None:
        user_candidate.email_confirmed = True
        if get_cluster_desc()['email_signup']:
            user_candidate.user_authorized = True
            url = flask.redirect(flask.url_for("login.confirmation_authorized_account"))
        else:
            url = flask.redirect(flask.url_for("login.confirmation_email"))
    close_session(db_session)
    return url


@login_blueprint.route("/logout")
@flask_login.login_required
def logout():
    flask_login.logout_user()
    return flask.redirect(flask.url_for("app.home"))

templates/login/confirmation_account_confirmation.html
{% extends "layout.html.jinja2" %}

{% block content %}
    <main role="main" class="container">
        <h1 class="mt-5">Congratulations!</h1>
        <p class="lead">Your email has been confirmed, we are going to setup your account. It may be ready with 5
            minutes.</p>
        <p>You can try to <a href="{{ url_for("login.login") }}">login</a> or go back to the
        <a href="{{ url_for("app.home") }}">home page</a>.</p>
    </main>
{% endblock %}

templates/login/confirmation_account_creation.html
{% extends "layout.html.jinja2" %}

{% block content %}
    <main role="main" class="container">
        <h1 class="mt-5">Congratulations!</h1>
        <p class="lead">Your account creation request has been processed and you should receive soon an email with a
            confirmation link. Once your email has been confirmed, we will proceed with the creation of your account.
        <p>You can go back to the <a href="{{ url_for("app.home") }}">home page</a>.</p>
    </main>
{% endblock %}

templates/login/confirmation_authorized_account.html
{% extends "layout.html.jinja2" %}

{% block content %}
    <main role="main" class="container">
        <h1 class="mt-5">Congratulations!</h1>
        <p class="lead">Your email has been confirmed, we are going to setup your account. It may be ready with 5
            minutes.</p>
        <p>You can try to <a href="{{ url_for("login.login") }}">login</a> or go back to the
        <a href="{{ url_for("app.home") }}">home page</a>.</p>
    </main>
{% endblock %}

templates/login/confirmation_created_account.html
{% extends "layout.html.jinja2" %}

{% block content %}
    <main role="main" class="container">
        <h1 class="mt-5">Congratulations!</h1>
        <p class="lead">Your account creation request has been processed and you should receive soon an email with a
            confirmation link. Once your email has been confirmed, we will proceed with the creation of your account.
        <p>You can go back to the <a href="{{ url_for("app.home") }}">home page</a>.</p>
    </main>
{% endblock %}

templates/login/confirmation_email.html
{% extends "layout.html.jinja2" %}

{% block content %}
    <main role="main" class="container">
        <p class="lead">Thank you to confirm your email address.</p>
        <a href="{{ url_for("app.home") }}">home page</a>.</p>
    </main>
{% endblock %}

templates/login/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url_for("static", filename="img/picloud.ico") }}">

    <title>Please login</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for("static", filename="css/bootstrap.min.css") }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for("static", filename="css/login.css") }}" rel="stylesheet">
</head>

<body class="text-center">
<form class="form-signin" action="{{ url_for("login.login") }}" method="POST">
      <img class="" src="{{ url_for("static", filename="img/logo.png") }}" alt="picloud fog logo" height="150">
        <br/>
        <br/>
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    {% if msg %}
        <div class="alert alert-danger" role="alert">
            {{ msg }}
        </div>
        <h2 class="form-signin-heading">Please sign in</h2>
    {% endif %}

    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" id="inputEmail" name="email"  class="form-control" placeholder="Email address"
        required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
    <input type="hidden" name="next_url" value="{{ next_url }}">

    <div class="form-group">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign In</button>
    </div>

    <div class="form-group">
        <p class="text-muted text-center">Do not have an account?
            <a href="{{ url_for("login.signup") }}">Sign Up!</a>
        </p>
    </div>
</form>
</body>
</html>


{% block body %}

{% endblock %}

templates/login/signup.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url_for("static", filename="img/picloud.ico") }}">

    <title>Please signup</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for("static", filename="css/bootstrap.min.css") }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for("static", filename="css/login.css") }}" rel="stylesheet">

    <style>
        .form-group {
            text-align: left;
        }
    </style>
</head>

<body class="text-center">
<form class="form-signin" action="{{ url_for("login.signup") }}" method="POST">
      <img class="" src="{{ url_for("static", filename="img/logo.png") }}" alt="picloud fog logo" height="150">
    <br/>
    <br/>
    <h2 class="form-signin-heading">Sign up</h2>

    <div class="form-group">
        <label>Email address</label>
        <input type="email" name="email" class="form-control" placeholder="Email address" required autofocus>
    </div>
    <div class="form-group">
        <label>First Name</label>
        <input type="text" name="firstname" class="form-control" placeholder="First name" required autofocus>
    </div>
    <div class="form-group">
        <label>Last name</label>
        <input type="text" name="lastname" class="form-control" placeholder="Last name" required autofocus>
    </div>
    <div class="form-group">
        <label>Password</label>
        <input type="password" name="password" class="form-control" placeholder="Password" required>
        <input type="password" name="confirm_password" class="form-control" placeholder="Confirm password" required>
        <input type="hidden" name="next_url" value="{{ next_url }}">
    </div>
    <div class="form-group">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
    </div>

    <div class="form-group">
        <p class="text-muted text-center">If you already have an account, please
            <a href="{{ url_for("login.login") }}">Login!</a>
        </p>
    </div>
</form>
</body>
</html>

templates/login/wait_admin_approval.html
{% extends "layout.html.jinja2" %}

{% block content %}
    <main role="main" class="container">
        <h1 class="mt-5">Account created!</h1>
        <p class="lead">Your registration request has been sent to the administrator.</p>
        <a href="{{ url_for("app.home") }}">Home Page</a>
    </main>
{% endblock %}