blueprints/login.py
from database.connector import open_session, close_session
from database.tables import User
from flask import Blueprint, render_template
from glob import glob
from lib.admin_decorators import admin_login_required
from lib.config_loader import get_cluster_desc
from lib.email_notification import get_email_configuration, send_confirmation_request
import flask, flask_login, logging, subprocess


login_blueprint = Blueprint('login', __name__, template_folder='templates')


@login_blueprint.route('/login', methods=['GET', 'POST'])
@login_blueprint.route('/login?msg=<msg>', methods=['GET', 'POST'])
def login(msg=None):
    from initialization import User as InitUser, bcrypt
    if flask.request.method == 'GET':
        next_url = flask.request.args.get("next")
        return render_template("login/login.html", next_url=next_url, msg=msg)
    email = flask.request.form.get('email', "")
    password = flask.request.form.get('password', "")
    next_url = flask.request.form.get('next_url', "/")
    db_session = open_session()
    user_account = db_session.query(User).filter(User.email == email).first()
    redirect_url = ''
    # User login
    if (user_account is not None and user_account.user_authorized and
            bcrypt.check_password_hash(user_account.password, password)):
        user = InitUser()
        user.id = email
        flask_login.login_user(user)
        redirect_url = next_url if (next_url is not None and next_url != "None") else flask.url_for("app.home")
    else:
        redirect_url = flask.url_for("login.login", msg="You are not authorized to log in")
    close_session(db_session)
    return flask.redirect(redirect_url)


@login_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    cluster_desc = get_cluster_desc()
    if flask.request.method == 'GET':
        next_url = flask.request.args.get("next")
        return render_template("login/signup.html", next_url=next_url)
    email = flask.request.form['email']
    firstname = flask.request.form['firstname']
    lastname = flask.request.form['lastname']
    password = flask.request.form['password']
    confirm_password = flask.request.form['confirm_password']
    db_session = open_session()
    existing_email = db_session.query(User).filter(User.email == email).all()
    if password != confirm_password:
        return 'The two passwords are not identical!<a href="/signup">Try again</a>'
    if len(existing_email) > 0:
        return "Your email address '%s' already exists. <a href='/'>Try to login</a>" % email
    email_filters = cluster_desc['email_filters']
    filter_ok = len(email_filters) == 0
    for f in email_filters:
        if f in email:
            filter_ok = True
    if not filter_ok:
        return 'Wrong email address.\
                Your domain name is not in the authorized domains.\
                Please contact the administrator or <a href="/signup">try with another email address</a>'
    user = User()
    user.email = email
    user.firstname = firstname
    user.lastname = lastname
    user._set_password = password
    db_session.add(user)
    close_session(db_session)
    email_conf = get_email_configuration()
    if len(email_conf['smtp_server_url']) > 0 and email_conf['smtp_server_url'] != 'no_config':
        # Send an email to confirm the user email address
        send_confirmation_request(email, firstname)
    if cluster_desc['email_signup']:
        redirect_url = flask.url_for("login.confirmation_created_account")
    else:
        redirect_url = flask.url_for("login.wait_admin_approval")
    return flask.redirect(redirect_url)


@login_blueprint.route('/confirmation_created_account')
def confirmation_created_account():
    return render_template("login/confirmation_created_account.html")


@login_blueprint.route('/wait_admin_approval')
def wait_admin_approval():
    return render_template("login/wait_admin_approval.html")


@login_blueprint.route('/confirmation_authorized_account')
def confirmation_authorized_account():
    return render_template("login/confirmation_authorized_account.html")


@login_blueprint.route('/confirmation_email')
def confirmation_email():
    return render_template("login/confirmation_email.html")


@login_blueprint.route('/confirm_email/token/<token>')
def confirm_email(token):
    logger = logging.getLogger("LOGIN")
    logger.info("Receive the token '%s' to confirm email" % token)
    db_session = open_session()
    user_candidate = db_session.query(User).filter(User.email_confirmation_token == token).first()
    url = "Bad request: could not find the given token '%s'" % (token)
    if user_candidate is not None:
        user_candidate.email_confirmed = True
        if get_cluster_desc()['email_signup']:
            user_candidate.user_authorized = True
            url = flask.redirect(flask.url_for("login.confirmation_authorized_account"))
        else:
            url = flask.redirect(flask.url_for("login.confirmation_email"))
    close_session(db_session)
    return url


@login_blueprint.route("/logout")
@flask_login.login_required
def logout():
    flask_login.logout_user()
    return flask.redirect(flask.url_for("app.home"))

blueprints/webapp.py
from database.connector import open_session, close_session
from database.states import select_process
from database.tables import Deployment, User
from flask import Blueprint
from flask_login import current_user
from glob import glob
from lib.admin_decorators import admin_login_required
from lib.config_loader import get_cluster_desc, load_cluster_desc
import datetime, flask, flask_login, json, random, shutil, string, subprocess


webapp_blueprint = Blueprint('app', __name__, template_folder='templates')

def new_password(stringLength=8):
    """Generate a random string of letters and digits """
    lettersAndDigits = string.ascii_letters + string.digits
    return ''.join(random.choice(lettersAndDigits) for i in range(stringLength))


@webapp_blueprint.route("/server/take/<string:server_info>")
@flask_login.login_required
def take(server_info):
    """ Create deployments in the initialized state """
    cluster_desc = get_cluster_desc()
    db_session = open_session()
    db_user = db_session.query(User).filter_by(email = current_user.id).first()
    # Delete previous deployments still in initialized state
    old_dep = db_session.query(Deployment).filter_by(user_id=db_user.id, state="initialized").delete()
    # Reserve the nodes to avoid other users to take them
    info = server_info.split(";")
    server_ids = info[0].split(",")
    server_names = info[1].replace(' ','').split(",")
    for n_name in server_names:
        new_deployment = Deployment()
        new_deployment.process = "deploy"
        new_deployment.state = "initialized"
        new_deployment.node_name = n_name
        new_deployment.user_id = db_user.id
        new_deployment.name = "initialized"
        db_session.add(new_deployment)
    close_session(db_session)
    # Reload the cluster decription to add new environments
    load_cluster_desc()
    return flask.render_template("form_take.html.jinja2",
                                 server_ids=server_ids,
                                 server_names=server_names,
                                 environments=[env 
                                     for env in cluster_desc["environments"].values() if env['type'] != 'hidden'])


@webapp_blueprint.route("/server/process_take/", methods=["POST"])
@flask_login.login_required
def process_take():
    """ Start deploying the selected environment """
    db_session = open_session()
    db_user = db_session.query(User).filter_by(email = current_user.id).first()
    deployments = db_session.query(Deployment).filter_by(user_id = db_user.id, state = "initialized").all()
    for d in deployments:
        d.name = flask.request.form.get("name")
        d.public_key = flask.request.form.get("public_key")
        d.init_script = flask.request.form.get("init_script")
        pwd = flask.request.form.get("sys_pwd").strip()
        if pwd:
            d.system_pwd = pwd[:50]
        else:
            d.system_pwd = new_password()
        d.environment = flask.request.form.get("environment")
        d.os_update = flask.request.form.get("os_update") == "on"
        d.duration = flask.request.form.get("duration_text")
        d.system_size = flask.request.form.get("more_space")
        d.start_date = datetime.datetime.now()
        d.state = select_process('deploy', d.environment)[0]
    close_session(db_session)
    return flask.redirect(flask.url_for("app.home"))


@webapp_blueprint.route("/server/cancel/")
@flask_login.login_required
def cancel():
    """ Cancel the deployment (that is in the initialized state) """
    db_session = open_session()
    db_user = db_session.query(User).filter_by(email = current_user.id).first()
    # Delete previous deployments still in initialized state
    old_dep = db_session.query(Deployment).filter_by(user_id=db_user.id, state="initialized").delete()
    close_session(db_session)
    return flask.redirect(flask.url_for("app.resources"))


@webapp_blueprint.route("/server/reboot/<string:n_name>")
@flask_login.login_required
def ask_reboot(n_name):
    """ Hard reboot the server """
    db_session = open_session()
    db_user = db_session.query(User).filter_by(email = current_user.id).first()
    # Verify the node belongs to my deployments
    my_deployment = db_session.query(Deployment).filter_by(user_id = db_user.id,
            node_name = n_name).filter(Deployment.state != "destroyed").first()
    if my_deployment is not None:
        # Do not remember the 'lost' state but the state before it
        if my_deployment.state != 'lost':
            my_deployment.temp_info = my_deployment.state
        my_deployment.process = "reboot"
        my_deployment.state = select_process("reboot", my_deployment.environment)[0]
    close_session(db_session)
    return flask.redirect(flask.url_for("app.home"))


@webapp_blueprint.route("/server/redeploy/<string:n_name>")
@flask_login.login_required
def ask_redeploy(n_name):
    """ Deploy again the environment on the server """
    db_session = open_session()
    db_user = db_session.query(User).filter_by(email = current_user.id).first()
    # Verify the node belongs to my deployments
    my_deployment = db_session.query(Deployment).filter_by(user_id = db_user.id,
            node_name = n_name).filter(Deployment.state != "destroyed").first()
    my_deployment.process = "deploy"
    my_deployment.state = select_process("deploy", my_deployment.environment)[0]
    close_session(db_session)
    return flask.redirect(flask.url_for("app.home"))


@webapp_blueprint.route("/server/release/<string:n_name>")
@flask_login.login_required
def ask_release_node(n_name):
    """ Delete the deployment associated to the server """
    db_session = open_session()
    db_user = db_session.query(User).filter_by(email = current_user.id).first()
    # Get the deployment associated to the node
    my_deployment = db_session.query(Deployment).filter_by(user_id = db_user.id,
            node_name = n_name).filter(Deployment.state != "destroyed").first()
    if my_deployment is not None:
        my_deployment.process = 'destroy'
        my_deployment.state = select_process('destroy', my_deployment.environment)[0]
    close_session(db_session)
    return flask.redirect(flask.url_for("app.home"))


@webapp_blueprint.route("/deployment/destroy/<string:deployment_ids>")
@flask_login.login_required
def ask_destruction(deployment_ids):
    """ Destroy multiple deployments from their id """
    db_session = open_session()
    db_user = db_session.query(User).filter_by(email = current_user.id).first()
    for d in deployment_ids.split(","):
        deployment = db_session.query(Deployment).filter_by(id = d, user_id = db_user.id).first()
        if deployment is not None:
            deployment.process = 'destroy'
            deployment.state = select_process('destroy', deployment.environment)[0]
    close_session(db_session)
    return flask.redirect(flask.url_for("app.home"))


@webapp_blueprint.route("/server/save_env/<string:n_name>")
@flask_login.login_required
def save_env(n_name):
    """ Display the form to configure the 'save environment' action """
    db_session = open_session()
    db_user = db_session.query(User).filter_by(email = current_user.id).first()
    deployment = db_session.query(Deployment).filter_by(user_id = db_user.id, node_name = n_name).filter(
            Deployment.state != "destroyed").first()
    env_name = deployment.environment
    close_session(db_session)
    return flask.render_template("form_save_env.html.jinja2",
                                 environment=env_name,
                                 node_name=n_name)


@webapp_blueprint.route("/server/build_env/", methods=["POST"])
@flask_login.login_required
def build_env():
    """ Execute the 'save environment' action => create a file image from the internal storage of the server"""
    cluster_desc = get_cluster_desc()
    db_session = open_session()
    db_user = db_session.query(User).filter_by(email = current_user.id).first()
    deployment = db_session.query(Deployment).filter_by(user_id = db_user.id,
            node_name=flask.request.form.get('node_name')).filter(Deployment.state != "destroyed").first()
    env = cluster_desc['environments'][deployment.environment]
    env['name'] = flask.request.form.get("user_env_name")
    env['img_name'] = env['name'] + '.img.gz'
    user_ssh_user = flask.request.form.get("user_ssh_user")
    if len(user_ssh_user) > 0:
        env['ssh_user'] = user_ssh_user
    env['type'] = 'user'
    env_file_path = cluster_desc['env_cfg_dir'] + env['name'].replace(' ', '_') + '.json'
    with open(env_file_path, 'w') as jsonfile:
        json.dump(env, jsonfile)
    deployment.process = 'save_env'
    deployment.state = 'img_part'
    deployment.temp_info = env['name']
    close_session(db_session)
    return flask.redirect(flask.url_for("app.home"))


@webapp_blueprint.route("/user/ssh_put/", methods=["POST"])
@flask_login.login_required
def ssh_put():
    """ Create/update the SSH key of the user account """
    my_ssh = flask.request.form.get("ssh_key")
    if my_ssh is not None and len(my_ssh) > 0:
        db_session = open_session()
        db_user = db_session.query(User).filter_by(email = current_user.id).first()
        db_user.ssh_key = my_ssh
        close_session(db_session)
    return flask.redirect(flask.url_for("app.user"))


@webapp_blueprint.route("/user/pwd_put/", methods=["POST"])
@flask_login.login_required
def pwd_put():
    """ Create/update the password of the user account """
    pwd = flask.request.form.get("password")
    confirm_pwd = flask.request.form.get("confirm_password")
    if pwd == confirm_pwd:
        db_session = open_session()
        db_user = db_session.query(User).filter_by(email = current_user.id).first()
        db_user._set_password = pwd
        close_session(db_session)
        return flask.redirect(flask.url_for("app.user"))
    else:
        return 'The two passwords are not identical!<a href="/user">Try again</a>'

templates/form_save_env.html.jinja2
{% extends "layout.html.jinja2" %}

{% block css %}
<script src="{{ url_for("static", filename="js/jquery-3.4.1.slim.min.js") }}"></script>
<script src="{{ url_for("static", filename="js/codemirror.js") }}"></script>
<link rel="stylesheet" href="{{ url_for("static", filename="css/codemirror.css") }}">
<script src="{{ url_for("static", filename="js/shell.js") }}"></script>

<style>
.CodeMirror {
    border: 1px solid #ced4da;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
</style>
{% endblock %}

{% block content %}
    <main role="main" class="container">
      <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h5>Please provide the following information to build your own environment:</h5>
        <br/>
        <form action="{{ url_for("app.build_env") }}" method="post">
            <div class="row">
              <div class="col-md-6 mb-3">
                <h6>Original environment</h6>
                <div class="border p-2 pl-3 text-secondary">{{ environment }}</div>
              </div>
              <div class="col-md-6 mb-3">
                <h6>Used node</h6>
                <div class="border p-2 pl-3 text-secondary">{{ node_name }}</div>
                <input type="hidden" id="node_name" name="node_name" value="{{ node_name }}" />
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 mb-3">
                <label>Name of your environment</label>
                <input class="form-control" id="user_env_name" name="user_env_name" type="text" required />
              </div>
              <div class="col-md-6 mb-3">
                <label>SSH User</label>
                <input class="form-control" id="user_ssh_user" name="user_ssh_user" type="text" />
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 mb-3">
                <input class="btn btn-primary float-right" type="submit" value="Deploy">
                <a class="btn btn-danger float-right mr-2" href="/">Cancel</a>
              </div>
            </div>
        </form>
      </div>
    </main>

    <script>
  var editor = CodeMirror.fromTextArea(document.getElementById('init_script'), {
    mode: 'shell',
    lineNumbers: true,
    matchBrackets: true
  });
  // Slider helpers
  var duration_slider = document.getElementById('duration');
  function displayValue(val) {
    var durationInput = document.getElementById('duration_text');
    durationInput.value = val;
  }
  function setSlider(val) {
    var durationSlider = document.getElementById('duration');
    durationSlider.value = val;
  }
</script>

{% endblock %}

templates/form_take.html.jinja2
{% extends "layout.html.jinja2" %}

{% block css %}
<script src="{{ url_for("static", filename="js/jquery-3.4.1.slim.min.js") }}"></script>
<script src="{{ url_for("static", filename="js/codemirror.js") }}"></script>
<link rel="stylesheet" href="{{ url_for("static", filename="css/codemirror.css") }}">
<script src="{{ url_for("static", filename="js/shell.js") }}"></script>

<style>
.CodeMirror {
    border: 1px solid #ced4da;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
</style>
{% endblock %}

{% block content %}
    <main role="main" class="container">
      <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6>Please provide the following information to deploy the following nodes:</h6>
        <div class="border-bottom border-gray pb-2 mb-0">
            {% for name in server_names %}
                <span class="node-list">{{ name }},</span>
            {% endfor %}
        </div>
        <br/>
        <form action="{{ url_for("app.process_take") }}" method="post">
            <div class="row">
              <div class="col-md-6 mb-3">
                <label>Environment</label>
                <div class="d-inline ml-os-update">
                    <label>Update the OS:</label>
                    <input type="checkbox" id="os_update" name="os_update" checked>
                </div>
                <select class="custom-select d-block w-100" id="environment" name="environment" required>
                    {% for environment in environments %}
                    <option value="{{ environment.name }}">{{ environment.name }}</option>
                    {% endfor %}
                </select>
              </div>
              <div class="col-md-6 mb-3">
                <label>Additional free space</label>
                <select id="more_space" name="more_space" class="custom-select d-block w-100">
                    <option value="8">Whole SD_CARD</option>
                    <option value="3072">3 Gigabytes</option>
                    <option value="2048">2 Gigabytes</option>
                    <option value="1024">1 Gigabytes</option>
                    <option value="500">500 Megabytes</option>
                    <option value="200">200 Megabytes</option>
                </select>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 mb-3">
                <label>Name</label>
                <input class="form-control" id="name" name="name" type="text" required></input>
              </div>
              <div class="col-md-6 mb-3">
                <label>System password</label>
                <input class="form-control" id="sys_pwd" name="sys_pwd" type="text"></input>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 mb-3">
                <label class="mr-2">Duration (hours):</label><input id="duration_text" name="duration_text"
                type="number" min="1" max="72" value="2" size="4" onchange="setSlider(this.value)" />
                <input type="range" id="duration" min="1" max="72" value="2" class="form-control slider_input"
                onchange="displayValue(this.value)" oninput="displayValue(this.value)" required>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 mb-3">
                <label>SSH Public key</label>
                <textarea class="form-control" rows="5" id="public_key" name="public_key"></textarea>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 mb-3">
                <label>Init script</label>
                <textarea class="form-control" rows="5" id="init_script" class="shell_code"
                    name="init_script"></textarea>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 mb-3">
                <input class="btn btn-primary float-right" type="submit" value="Deploy">
                <a class="btn btn-danger float-right mr-2" href="/server/cancel">Cancel</a>
              </div>
            </div>
        </form>
      </div>
    </main>

    <script>
  var editor = CodeMirror.fromTextArea(document.getElementById('init_script'), {
    mode: 'shell',
    lineNumbers: true,
    matchBrackets: true
  });
  // Slider helpers
  var duration_slider = document.getElementById('duration');
  function displayValue(val) {
    var durationInput = document.getElementById('duration_text');
    durationInput.value = val;
  }
  function setSlider(val) {
    var durationSlider = document.getElementById('duration');
    durationSlider.value = val;
  }
</script>

{% endblock %}

templates/user_vuejs.html.jinja2
{% extends "layout.html.jinja2" %}

{% block content %}

    <div id="app" v-cloak>
        <main role="main" class="container my-3 p-3 bg-white rounded shadow-sm">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                        aria-controls="home" aria-selected="true">Account Info</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" id="password-tab" data-toggle="tab" href="#password" role="tab"
                            aria-controls="password" aria-selected="false">Password</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" id="email-tab" data-toggle="tab" href="#email" role="tab"
                        aria-controls="email" aria-selected="false">Email</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="ssh-tab" data-toggle="tab" href="#ssh" role="tab"
                        aria-controls="ssh" aria-selected="false">SSH Key</a>
                </li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content grid-user">
                <div class="tab-pane active pt-2 pane-user" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <b class="text-info">Fistname</b>: [[ user.firstname ]]<br/>
                    <b class="text-info">Lastname</b>: [[ user.lastname ]]<br/>
                    <b class="text-info">Email</b>: [[ user.email ]]<br/>
                    <span v-if="[[ user.ssh ]] == ''">
                        <b class="text-info">SSH key</b>: No SSH key registered<br/>
                    </span>
                    <span v-if="[[ user.ssh ]] != ''">
                        <b class="text-info">SSH key</b>
                        : ...[[ user.ssh.substring(user.ssh.length, user.ssh.length - 30) ]]<br/>
                    </span>
                    <b class="text-info">Status</b>: [[ user.status ]]<br/>
                </div>
                <div class="tab-pane pt-2" id="password" role="tabpanel" aria-labelledby="password-tab">
                    <div class="container">
                        <form action="{{ url_for("app.pwd_put") }}" method="post">
                            <div class="row" style="width: 400px;">
                                <div class="col">New password</div>
                                <div class="col"><input name="password" type="password"></div>
                            </div>
                            <div class="row" style="width: 400px;">
                                <div class="col">Confirm password</div>
                                <div class="col"><input name="confirm_password" type="password"></div>
                            </div>
                            <div class="row text-center" style="width: 400px;">
                                <div class="col">
                                    <button type="submit" value="submit" class="btn btn-info btn-user">
                                        Change password
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="tab-pane pt-2" id="email" role="tabpanel" aria-labelledby="email-tab">
                    <div class="container">
                        <div class="row">
                            <div class="col">New login email</div>
                            <div class="col"><input type='password'></div>
                        </div>
                        <div class="row text-center">
                            <div class="col">
                                <button class="btn btn-info btn-user">Change email</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane pt-2" id="ssh" role="tabpanel" aria-labelledby="ssh-tab">
                    <div class="container">
                        <form action="{{ url_for("app.ssh_put") }}" method="post">
                            <div class="row">
                                <div class="col">
                                    <b class="text-info">Current SSH key</b><br/>
                                </div>
                                <div class="col">
                                    <b class="text-info">New SSH key</b><br/>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div style="width: 450px; word-wrap: break-word;">
                                        [[ user.ssh ]]
                                    </div>
                                </div>
                                <div class="col">
                                    <textarea type="text" id="ssh_key" name="ssh_key" rows=10 class="form-control
                                        input-user"></textarea><br/>
                                </div>
                            </div>
                            <div class="row">
                            </div>
                            <div class="row">
                                <div class="col center-block text-center">
                                    <button type="submit" value="submit" class="btn btn-info btn-user">
                                        Change ssh key
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div><!-- tab-content -->
        </main>
    </div>
    <script src="{{ url_for("static", filename="js/vue") }}"></script>
    <script>
        function addInputField() {
            var divContent = document.getElementById('textvalues');
            var fieldId = 'ifield-id';
            var inputField = document.getElementById(fieldId);
            if(inputField == null) {
                // Create the input field
                var inputText = document.createElement("textarea");
                inputText.id = fieldId;
                inputText.rows = 9;
                inputText.className = "input-user";
                // Create the confirm button
                var saveButton = document.createElement("button");
                saveButton.innerHTML = 'Confirm';
                saveButton.addEventListener ("click", function() {
                    alert("did something");
                });
                saveButton.className = 'btn btn-info btn-user mb-5';
                // Append the new elements
                divContent.appendChild(inputText);
                divContent.appendChild(document.createElement('br'));
                divContent.appendChild(saveButton);

            }
        }
        const app = new Vue({
            el: '#app',
            data: {
                term: '',
                user: [],
                noResults: false,
                loading: true
            },
            methods: {
                fetch_my_user: function () {
                    fetch("{{ url_for("app_api.user_info") }}")
                        .then(res => res.json())
                        .then(res => {
                            this.user = res.my_user;
                        });
                },
                reload_all_data: function () {
                    this.fetch_my_user();
                    this.loading = false;
                }
            },
            beforeMount: function () {
                this.reload_all_data();
                this.loading = true;
            },
            delimiters: ['[[', ']]']
        });
    </script>
{% endblock %}